config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :purchases

  resources :material_purchases

  resources :units

  resources :materials

  resources :product_materials

  resources :product_categories

  resources :categories

  resources :product_sales

  resources :sales

  resources :products

  resources :discounts

  resources :users

  resources :clients

  root to: 'application#index'

  post '/login' => 'application#login'

  get '/index' => 'application#index'

  get '/logout' => 'application#logout'

  get '/pdf' => 'materials#pdf'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, through: :products_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :sales, dependent: :destroy
end

app/models/discount.rb
class Discount < ActiveRecord::Base
	has_many :product_sales
end

app/models/material.rb
class Material < ActiveRecord::Base

	validates :available, numericality: { greater_than: 0, message: 'La cantidad debe ser mayor que 0' }
	validates :name, presence: {presence: true, message: 'Debe contener un nombre'}
	has_many :products_materials
	has_many :products, through: :products_materials

	has_many :materials_purchases
	has_many :purchases, through: :materials_purchases

	has_one :unit, :class_name => Unit, :foreign_key => "id", :primary_key => "unit_id"

	def self.to_csv
    CSV.generate do |csv|
      csv << column_names
	      all.each do |material|
	        csv << material.attributes.values_at(*column_names)
	      end
		end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base

	
	has_many :product_sales	
	has_many :sales, through: :product_sales

	has_many :product_categories       
	has_many :categories, through: :product_categories

	has_many :product_materials
	has_many :materials, through: :product_materials

	accepts_nested_attributes_for :materials
	accepts_nested_attributes_for :product_materials

	accepts_nested_attributes_for :categories
	accepts_nested_attributes_for :product_categories

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	belongs_to :product
	belongs_to :category
end

app/models/product_material.rb
class ProductMaterial < ActiveRecord::Base
	belongs_to :product
	belongs_to :material

	accepts_nested_attributes_for :material
end

app/models/product_sale.rb
class ProductSale < ActiveRecord::Base
	belongs_to :sale
	belongs_to :product
	has_one :discount

	accepts_nested_attributes_for :product, :reject_if => :all_blank
	accepts_nested_attributes_for :sale, :reject_if => :all_blank
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

	

	belongs_to :user
	belongs_to :supplier

	has_many :material_purchases
	has_many :materials, through: :material_purchases

	accepts_nested_attributes_for :materials
	accepts_nested_attributes_for :material_purchases
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	
	after_validation :checar_tablas

	def checar_tablas





	end


	belongs_to :client
	belongs_to :user
	
	has_many :product_sales
	has_many :products, through: :product_sales, :class_name => "Product"

	accepts_nested_attributes_for :products
	accepts_nested_attributes_for :product_sales

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :purchases
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :materials
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sales, dependent: :destroy
	has_many :purchases
end

app/controllers/product_materials_controller.rb
class ProductMaterialsController < ApplicationController
  before_action :set_product_material, only: [:show, :edit, :update, :destroy]

  # GET /product_materials
  # GET /product_materials.json
  def index
    @product_materials = ProductMaterial.all
  end

  # GET /product_materials/1
  # GET /product_materials/1.json
  def show
  end

  # GET /product_materials/new
  def new
    @product_material = ProductMaterial.new
  end

  # GET /product_materials/1/edit
  def edit
  end

  # POST /product_materials
  # POST /product_materials.json
  def create
    @product_material = ProductMaterial.new(product_material_params)

    respond_to do |format|
      if @product_material.save
        format.html { redirect_to @product_material, notice: 'Product material was successfully created.' }
        format.json { render :show, status: :created, location: @product_material }
      else
        format.html { render :new }
        format.json { render json: @product_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_materials/1
  # PATCH/PUT /product_materials/1.json
  def update
    respond_to do |format|
      if @product_material.update(product_material_params)
        format.html { redirect_to @product_material, notice: 'Product material was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_material }
      else
        format.html { render :edit }
        format.json { render json: @product_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_materials/1
  # DELETE /product_materials/1.json
  def destroy
    @product_material.destroy
    respond_to do |format|
      format.html { redirect_to product_materials_url, notice: 'Product material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_material
      @product_material = ProductMaterial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_material_params
      params.require(:product_material).permit(:units)
    end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/product_materials_helper.rb
module ProductMaterialsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_materials/_form.html.erb
<%= form_for(@product_material) do |f| %>
  <% if @product_material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_material.errors.count, "error") %> prohibited this product_material from being saved:</h2>

      <ul>
      <% @product_material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :units %><br>
    <%= f.number_field :units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_materials/edit.html.erb
<h1>Editing product_material</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_material %> |
<%= link_to 'Back', product_materials_path %>

app/views/product_materials/index.html.erb
<h1>Listing product_materials</h1>

<table>
  <thead>
    <tr>
      <th>Units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_materials.each do |product_material| %>
      <tr>
        <td><%= product_material.units %></td>
        <td><%= link_to 'Show', product_material %></td>
        <td><%= link_to 'Edit', edit_product_material_path(product_material) %></td>
        <td><%= link_to 'Destroy', product_material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product material', new_product_material_path %>

app/views/product_materials/new.html.erb
<h1>New product_material</h1>

<%= render 'form' %>

<%= link_to 'Back', product_materials_path %>

app/views/product_materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Units:</strong>
  <%= @product_material.units %>
</p>

<%= link_to 'Edit', edit_product_material_path(@product_material) %> |
<%= link_to 'Back', product_materials_path %>