config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :purchases

  resources :material_purchases

  resources :units

  resources :materials

  resources :product_materials

  resources :product_categories

  resources :categories

  resources :product_sales

  resources :sales

  resources :products

  resources :discounts

  resources :users

  resources :clients

  root to: 'application#index'

  post '/login' => 'application#login'

  get '/index' => 'application#index'

  get '/logout' => 'application#logout'

  get '/pdf' => 'materials#pdf'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, through: :products_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :sales, dependent: :destroy
end

app/models/discount.rb
class Discount < ActiveRecord::Base
	has_many :product_sales
end

app/models/material.rb
class Material < ActiveRecord::Base

	validates :available, numericality: { greater_than: 0, message: 'La cantidad debe ser mayor que 0' }
	validates :name, presence: {presence: true, message: 'Debe contener un nombre'}
	has_many :products_materials
	has_many :products, through: :products_materials

	has_many :materials_purchases
	has_many :purchases, through: :materials_purchases

	has_one :unit, :class_name => Unit, :foreign_key => "id", :primary_key => "unit_id"

	def self.to_csv
    CSV.generate do |csv|
      csv << column_names
	      all.each do |material|
	        csv << material.attributes.values_at(*column_names)
	      end
		end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base

	
	has_many :product_sales	
	has_many :sales, through: :product_sales

	has_many :product_categories       
	has_many :categories, through: :product_categories

	has_many :product_materials
	has_many :materials, through: :product_materials

	accepts_nested_attributes_for :materials
	accepts_nested_attributes_for :product_materials

	accepts_nested_attributes_for :categories
	accepts_nested_attributes_for :product_categories

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	belongs_to :product
	belongs_to :category
end

app/models/product_material.rb
class ProductMaterial < ActiveRecord::Base
	belongs_to :product
	belongs_to :material

	accepts_nested_attributes_for :material
end

app/models/product_sale.rb
class ProductSale < ActiveRecord::Base
	belongs_to :sale
	belongs_to :product
	has_one :discount

	accepts_nested_attributes_for :product, :reject_if => :all_blank
	accepts_nested_attributes_for :sale, :reject_if => :all_blank
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

	

	belongs_to :user
	belongs_to :supplier

	has_many :material_purchases
	has_many :materials, through: :material_purchases

	accepts_nested_attributes_for :materials
	accepts_nested_attributes_for :material_purchases
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	
	after_validation :checar_tablas

	def checar_tablas





	end


	belongs_to :client
	belongs_to :user
	
	has_many :product_sales
	has_many :products, through: :product_sales, :class_name => "Product"

	accepts_nested_attributes_for :products
	accepts_nested_attributes_for :product_sales

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :purchases
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :materials
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sales, dependent: :destroy
	has_many :purchases
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @nombre = 'Control de usuarios del sistema'
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unidad creada.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unidad actualizada.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unidad destruida.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :abbr)
    end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :abbr %><br>
    <%= f.text_area :abbr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.abbr %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Abbr:</strong>
  <%= @unit.abbr %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>