config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :purchases

  resources :material_purchases

  resources :units

  resources :materials

  resources :product_materials

  resources :product_categories

  resources :categories

  resources :product_sales

  resources :sales

  resources :products

  resources :discounts

  resources :users

  resources :clients

  root to: 'application#index'

  post '/login' => 'application#login'

  get '/index' => 'application#index'

  get '/logout' => 'application#logout'

  get '/pdf' => 'materials#pdf'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, through: :products_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :sales, dependent: :destroy
end

app/models/discount.rb
class Discount < ActiveRecord::Base
	has_many :product_sales
end

app/models/material.rb
class Material < ActiveRecord::Base

	validates :available, numericality: { greater_than: 0, message: 'La cantidad debe ser mayor que 0' }
	validates :name, presence: {presence: true, message: 'Debe contener un nombre'}
	has_many :products_materials
	has_many :products, through: :products_materials

	has_many :materials_purchases
	has_many :purchases, through: :materials_purchases

	has_one :unit, :class_name => Unit, :foreign_key => "id", :primary_key => "unit_id"

	def self.to_csv
    CSV.generate do |csv|
      csv << column_names
	      all.each do |material|
	        csv << material.attributes.values_at(*column_names)
	      end
		end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base

	
	has_many :product_sales	
	has_many :sales, through: :product_sales

	has_many :product_categories       
	has_many :categories, through: :product_categories

	has_many :product_materials
	has_many :materials, through: :product_materials

	accepts_nested_attributes_for :materials
	accepts_nested_attributes_for :product_materials

	accepts_nested_attributes_for :categories
	accepts_nested_attributes_for :product_categories

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
	belongs_to :product
	belongs_to :category
end

app/models/product_material.rb
class ProductMaterial < ActiveRecord::Base
	belongs_to :product
	belongs_to :material

	accepts_nested_attributes_for :material
end

app/models/product_sale.rb
class ProductSale < ActiveRecord::Base
	belongs_to :sale
	belongs_to :product
	has_one :discount

	accepts_nested_attributes_for :product, :reject_if => :all_blank
	accepts_nested_attributes_for :sale, :reject_if => :all_blank
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

	

	belongs_to :user
	belongs_to :supplier

	has_many :material_purchases
	has_many :materials, through: :material_purchases

	accepts_nested_attributes_for :materials
	accepts_nested_attributes_for :material_purchases
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	
	after_validation :checar_tablas

	def checar_tablas





	end


	belongs_to :client
	belongs_to :user
	
	has_many :product_sales
	has_many :products, through: :product_sales, :class_name => "Product"

	accepts_nested_attributes_for :products
	accepts_nested_attributes_for :product_sales

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :purchases
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :materials
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sales, dependent: :destroy
	has_many :purchases
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    @nombre = 'Ventas'
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @nombre = 'Detalles de la venta'
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @sale.product_sales.build
    @sale.products.build
    @nombre = 'Nueva venta'
  end

  # GET /sales/1/edit
  def edit
    @sale= Sale.find(params[:id])
    @sale.product_sales.build
    @sale.products.build
    @nombre = 'Editar venta'
  end

  # POST /sales
  # POST /sales.json
  def create
    @nombre = 'Nueva venta'
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Venta creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    @nombre = 'Editar venta'
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Venta editada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @nombre = 'Eliminar venta'
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Venta eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(
        :id, :saleDate, :client_id, :user_id, 
        product_sales_attributes: [:product_id, :cantidad, :_destroy,
          products_attributes: [:id, :name, :price] ] 
      )
    end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sales/_client_fields.html.slim
.nested-fields
  = f.input :name, label: 'Nombre'
  = f.input :address, label: 'Dirección'
  = link_to_remove_association "Quitar cliente", f

app/views/sales/_form.html.slim
= simple_form_for @sale, html: {class: 'form-horizontal'} do |f|
  = f.input :saleDate, label: 'Fecha de venta '

  ul.nav.nav-tabs role='tablist'

    li
      = link_to 'Cliente', '#client', data: {toggle: 'tab'}
    li
      = link_to 'Productos', '#products', data: {toggle: 'tab'}

  .tab-content
   
    #client.tab-pane role='tabpanel'
      #client_from_list
        = f.association :client, label: 'Cliente', collection: Client.order(:name), prompt: 'Elegir existente'
      = link_to_add_association 'Agregar nuevo', f, :client

    #products.tab-pane role='tabpanel'
      = f.simple_fields_for :product_sales do |product_sale|
        = render 'product_sale_fields', :f => product_sale
	    = link_to_add_association 'Agregar producto', f, :product_sales

  .actions
    = f.button :submit, "Finalizar venta", :disable_with => 'Espere un momento ...'

app/views/sales/_product_fields.html.slim
.nested-fields
  = f.input :name, :hint => 'Cómo se llama el producto', :label => false

app/views/sales/_product_sale_fields.html.slim
.nested-fields.product-sale-fields
  #product_from_list 
  = f.association :product, label: "Producto existente",  label_method: :name, value_method: :id
  = f.input :cantidad
  = link_to_remove_association "Borrar producto de venta", f

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<table>
  <thead>
    <tr>
      <th>Fecha de venta</th>
      <th> Cliente</th>
      <th> Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.saleDate %></td>
        <td><%= sale.client.name %></td>
        <td>$ <%= 

          total = Sale.select("sales.id, sum(products.price*product_sales.cantidad) as total_price").joins(:product_sales, :products).where("product_sales.sale_id = ?", sale.id).group("sales.id").first.read_attribute("total_price")
          
          
          
         %></td>
        <td><%= link_to 'Detalles', sale %></td>
        <td><%= link_to 'Editar', edit_sale_path(sale) %></td>
        <td><%= link_to 'Eliminar', sale, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva venta', new_sale_path %>

app/views/sales/new.html.erb
<%= render 'form' %>

<%= link_to 'Atrás', sales_path %>

app/views/sales/old_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :saleDate %><br>
    <%= f.date_select :saleDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Saledate:</strong>
  <%= @sale.saleDate %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>